apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
      env: prod
  replicas: 4
  template:
    metadata: 
      name: nginx-2
      labels:
        env: prod
        app: myapp
        tier: frontend
    spec:
      containers: 
      - name: nginx
        image: nginx