apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
      env: prod
  replicas: 3
  template:
    metadata: 
      name: nginx-2
      labels:
        env: prod
        app: myapp
        tier: frontend
    spec:
      containers: 
      - name: nginx
        image: nginx
  